// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfpwxdesllltycgwhxhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcHd4ZGVzbGxsdHljZ3doeGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDAzNTcsImV4cCI6MjA3MDM3NjM1N30.pOaKvcHqVdNOIxckWexZ0Mrf6Ozlnecw2LLlAVzal3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});